# Generated by Django 4.2.7 on 2024-02-27 09:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0002_alter_patientjourney_name_alter_trace_event_type"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="patientjourney",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="patientjourney",
            name="name",
            field=models.CharField(
                help_text="If no name is provided, the name of the uploaded file will be used.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientjourney",
            name="patient_journey",
            field=models.TextField(),
        ),
    ]
