# Generated by Django 4.2.7 on 2024-03-19 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0008_rename_event_information_event_activity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cohort",
            old_name="sex",
            new_name="gender",
        ),
    ]
