# Generated by Django 5.0 on 2024-04-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0016_alter_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientjourney",
            name="name",
            field=models.CharField(
                help_text="The name represents a unique title describing the content of the patient journey.",
                max_length=100,
                unique=True,
            ),
        ),
    ]
