# Generated by Django 4.2.7 on 2024-02-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientJourney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the patient journey.", max_length=100
                    ),
                ),
                ("patient_journey", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Trace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_information", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Sym_On", "Symptom onset"),
                            ("Sym_Off", "Symptom offset"),
                            ("Inf", "Infection start/end"),
                            ("Diag", "Diagnosis"),
                            ("Doc", "Doctor visit"),
                            ("Treat", "Treatment"),
                            ("Hos_Ad", "Hospital Admission"),
                            ("Hos_Dis", "Hospital Discharge"),
                            ("Med", "Medication"),
                            ("Change", "Lifestyle change"),
                            ("Feel", "Feelings"),
                        ],
                        max_length=25,
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("duration", models.DurationField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Home", "Home"),
                            ("Hos", "Hospital"),
                            ("Doc", "Doctors"),
                        ],
                        max_length=25,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "patient_journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace",
                        to="extraction.patientjourney",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dfg", models.ImageField(null=True, upload_to="")),
                ("xes", models.FileField(null=True, upload_to="")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "traces",
                    models.ManyToManyField(
                        related_name="event_log", to="extraction.trace"
                    ),
                ),
            ],
        ),
    ]
