# Generated by Django 4.2.7 on 2024-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientjourney",
            name="name",
            field=models.CharField(
                help_text="If no name is provided, the name of the uploaded file will be used.",
                max_length=100,
                verbose_name="Name for your patient journey",
            ),
        ),
        migrations.AlterField(
            model_name="trace",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Symptom Onset", "Symptom Onset"),
                    ("Symptom Offset", "Symptom Offset"),
                    ("Diagnosis", "Diagnosis"),
                    ("Doctor Visit", "Doctor Visit"),
                    ("Treatment", "Treatment"),
                    ("Hospital Admission", "Hospital Admission"),
                    ("Hospital Discharge", "Hospital Discharge"),
                    ("Medication", "Medication"),
                    ("Lifestyle Change", "Lifestyle Change"),
                    ("Feelings", "Feelings"),
                ],
                max_length=25,
            ),
        ),
    ]
