# Generated by Django 4.2.7 on 2024-03-07 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0004_alter_patientjourney_patient_journey"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="trace",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="trace",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="end",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="event_information",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="last_modified",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="location",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="start",
        ),
        migrations.AlterField(
            model_name="patientjourney",
            name="patient_journey",
            field=models.FileField(upload_to=""),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_information", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Symptom Onset", "Symptom Onset"),
                            ("Symptom Offset", "Symptom Offset"),
                            ("Diagnosis", "Diagnosis"),
                            ("Doctor Visit", "Doctor Visit"),
                            ("Treatment", "Treatment"),
                            ("Hospital Admission", "Hospital Admission"),
                            ("Hospital Discharge", "Hospital Discharge"),
                            ("Medication", "Medication"),
                            ("Lifestyle Change", "Lifestyle Change"),
                            ("Feelings", "Feelings"),
                        ],
                        max_length=25,
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("duration", models.DurationField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Home", "Home"),
                            ("Hos", "Hospital"),
                            ("Doc", "Doctors"),
                        ],
                        max_length=25,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="extraction.trace",
                    ),
                ),
            ],
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
