# Generated by Django 4.2.7 on 2024-03-14 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0005_alter_trace_managers_remove_trace_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "trace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cohort",
                        serialize=False,
                        to="extraction.trace",
                    ),
                ),
                ("age", models.IntegerField()),
                ("sex", models.CharField(max_length=25)),
                ("origin", models.CharField(max_length=50)),
                ("condition", models.CharField(max_length=50)),
                ("preexisting_condition", models.CharField(max_length=100)),
            ],
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="patientjourney",
            name="name",
            field=models.CharField(
                help_text="This is a unique title describing the content of the patient journey.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="EventLog",
        ),
    ]
