# Generated by Django 4.2.7 on 2024-03-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0006_cohort_alter_patientjourney_name_delete_eventlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="trace",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="patientjourney",
            name="patient_journey",
            field=models.TextField(),
        ),
    ]
