# Generated by Django 4.2.7 on 2024-03-18 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0007_trace_last_modified_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_information",
            new_name="activity",
        ),
    ]
