# Generated by Django 4.2.7 on 2024-03-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0009_rename_sex_cohort_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cohort",
            name="trace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cohort",
                to="extraction.trace",
            ),
        ),
    ]
