# Generated by Django 4.2.7 on 2024-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0010_cohort_id_alter_cohort_trace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="condition",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="gender",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="origin",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="preexisting_condition",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
