# Generated by Django 4.2.7 on 2024-03-19 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0013_alter_cohort_trace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cohort",
            name="trace",
        ),
    ]
