# Generated by Django 4.2.7 on 2024-04-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0017_alter_patientjourney_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="category",
            field=models.CharField(default="zero-shot", max_length=100),
            preserve_default=False,
        ),
    ]
