# Generated by Django 4.2.11 on 2024-04-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0018_metrics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metrics',
            new_name='Metric',
        ),
    ]
