# Generated by Django 4.2.11 on 2024-05-04 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0019_alter_prompt_category_alter_prompt_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_relevance", models.CharField(max_length=25)),
                ("timestamp_correctness", models.BooleanField()),
                (
                    "correctness_confidence",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="extraction.event",
                    ),
                ),
            ],
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
