# Generated by Django 5.0.2 on 2024-05-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0019_rename_metrics_metric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="correctness_confidence",
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
