# Generated by Django 5.0.2 on 2024-05-03 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0019_alter_prompt_category_alter_prompt_name_and_more"),
        ("extraction", "0020_alter_metric_correctness_confidence"),
    ]

    operations = []
