# Generated by Django 4.2.11 on 2024-05-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0020_metric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Symptom Onset", "Symptom Onset"),
                    ("Symptom Offset", "Symptom Offset"),
                    ("Diagnosis", "Diagnosis"),
                    ("Doctor Visit", "Doctor Visit"),
                    ("Treatment", "Treatment"),
                    ("Hospital Admission", "Hospital Admission"),
                    ("Hospital Discharge", "Hospital Discharge"),
                    ("Medication", "Medication"),
                    ("Lifestyle Change", "Lifestyle Change"),
                    ("Feelings", "Feelings"),
                    ("N/A", "N/A"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                choices=[
                    ("Home", "Home"),
                    ("Hospital", "Hospital"),
                    ("Doctors", "Doctors"),
                    ("N/A", "N/A"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="activity_relevance",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="metric",
            name="correctness_confidence",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name="metric",
            name="timestamp_correctness",
            field=models.BooleanField(null=True),
        ),
    ]
