# Generated by Django 4.2.7 on 2024-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0021_alter_event_event_type_alter_event_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cohort",
            name="gender",
        ),
        migrations.AddField(
            model_name="cohort",
            name="sex",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="condition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="origin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="preexisting_condition",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
