# Generated by Django 4.2.13 on 2024-05-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0021_alter_event_event_type_alter_event_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace',
            name='cohort',
        ),
        migrations.AddField(
            model_name='cohort',
            name='condition_snomed_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='preexisting_condition_snomed_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='trace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohort', to='extraction.trace'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='preexisting_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
