# Generated by Django 4.2.13 on 2024-05-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0022_add_snomed_trace_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='gender',
        ),
        migrations.AddField(
            model_name='cohort',
            name='sex',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
