# Generated by Django 5.0.2 on 2024-05-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0022_remove_trace_cohort_cohort_trace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='gender',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='preexisting_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
