# Generated by Django 5.0.2 on 2024-05-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0022_remove_cohort_gender_cohort_sex_alter_cohort_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace',
            name='cohort',
        ),
        migrations.AddField(
            model_name='cohort',
            name='trace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohort', to='extraction.trace'),
        ),
    ]
