# Generated by Django 4.2.11 on 2024-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0023_alter_cohort_age_alter_cohort_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="condition_snomed_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cohort",
            name="preexisting_condition_snomed_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
