name: Extraction Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai==1.5.0
        pip install pm4py~=2.7.10.3
        pip install pandas~=2.2.1
        pip install numpy~=1.26.4
    - name: Run extraction tests
      run: python tracex_project/manage.py test tracex_project/extraction
